### ISSUE TITLE
Questions about running Liger in your dataset

### ISSUE THREAD

**Issue by HelloWorldLTY** [Svvord/iMAP#1]
Sorry to disturb you now, I saw that you used LIGER as a benchmark in your paper, but could you please talk more about it? I have tried many different ways but I could not run liger in jupyter notebook, because it seems that I could not just input the np.array matrix in to the model. However, in kbet and lisi rate, I successfully calculated them. Could you please help me solve this problem? I will be very grateful!

**Comment by Svvord** [comment]
> Sorry to disturb you now, I saw that you used LIGER as a benchmark in your paper, but could you please talk more about it? I have tried many different ways but I could not run liger in jupyter notebook, because it seems that I could not just input the np.array matrix in to the model. However, in kbet and lisi rate, I successfully calculated them. Could you please help me solve this problem? I will be very grateful!

Not all of these comparison methods can be run on python, some of them we used the R language, and the obtained calculation results were then compared for subsequent validation. LIGER is one of them, and the method has recently been updated.  It is recommended that you use the R version of LIGER and then run the subsequent metric calculations.
