### ISSUE TITLE
axis 0 is out of bounds for array of dimension 0

### ISSUE THREAD

**Issue by galicae** [Svvord/iMAP#3]
Hi! I wanted to give iMAP a try, but fell at the first hurdle. I installed using `pip` and tried to run iMAP on my `AnnData` object.

```
import imap
test = adata[:, var_genes].copy()
EC, ec_data = imap.stage1.iMAP_fast(test, key='batch', n_epochs=200)
```

I get an `AxisError: axis 0 is out of bounds for array of dimension 0`, thrown from `extract_data`. I think this happens because in line 311 you subset the `.X` slot but make it an array. However, subsets of a matrix are already matrices, so later, when you try to access it (line 127), it has an array that contains no data. Please advise :D

**Comment by Svvord** [comment]
Can you please print the `test` message after copying and the complete error report? It seems to me that this error is because your `test` is empty, or the number of  `var_genes ` is one. And please make sure that the `test.obs['batch']` has the correct information in it.

**Comment by krushnapavan9** [comment]
I encountered a similar issue when my adata.X is scipy.sparce matrix but was able to resolve when I convert it to numpy array :partying_face:
